Develop
TitovEvgeni/AudioPlayer pull request #2
Opened 2021-03-16 07:37 UTC by TitovEvgeni

MVC music player application PR.

2021-03-16 10:22 UTC, ekazimirova requested changes

2021-03-16 10:22 UTC, ekazimirova commented on AudioPlayer/AppDelegate.swift
> +//  Created by Titov, Evgeny on 11.03.21.
please remove any javadoc

2021-03-16 10:22 UTC, ekazimirova commented on AudioPlayer/AppDelegate.swift
> +        IQKeyboardManager.shared.toolbarManageBehaviour = .byTag
think how it's better to move in separated method or even better in some entity-manager

2021-03-16 10:22 UTC, ekazimirova commented on AudioPlayer/Custom View/Cells/Table View/MusicCell/MusicTableViewCell.swift
> +        self.separatorInset = UIEdgeInsets(top: 0, left: 15, bottom: 0, right: 15)
avoid any const/magic numbers inside code. Are we sure that we can just in such case set edgeinsets through code?

2021-03-16 10:22 UTC, ekazimirova commented on AudioPlayer/GoogleService-Info.plist
> +	<string>276218290231-oropuo20n1mh5mq34modbnrfe4dabau8.apps.googleusercontent.com</string>
it's better not to save any secure data inside git. For more info please read about security in the projects https://wiki.itransition.com/pages/viewpage.action?pageId=669273261 (if you don't have access let me know)

2021-03-16 10:22 UTC, ekazimirova commented on AudioPlayer/Helpers/LinearGradient.swift
> +        gradient.endPoint = CGPoint(x: 1, y: 0.5)
separate method with start/end point

2021-03-16 10:22 UTC, ekazimirova commented on AudioPlayer/Objects/RequestHandler.swift
> +    private let headers: HTTPHeaders = ["api-key" : "api-key"]
what will be if we have more than one header? think how it's better to move in separate place

2021-03-16 10:22 UTC, ekazimirova commented on AudioPlayer/Screens/Music/Controller/MusicViewController.swift
> +        FirebaseHandler().read { [weak self] (response: [String: MusicFirebase]?) in
in future it should be some entity-manager which can make it (presenter) :)

2021-03-16 10:22 UTC, ekazimirova commented on AudioPlayer/Screens/Player/Controller/PlayerViewController.swift
> +            trackImage.isHidden = false
think about extensition for any view for hidding

2021-03-16 10:22 UTC, ekazimirova commented on AudioPlayer/Screens/Player/Controller/PlayerViewController.swift
> +            ? sender.setTitle("Pause", for: .normal)
RSwift is very cool think for adding string in one place

2021-03-16 10:22 UTC, ekazimirova commented on Podfile
> +  pod 'Firebase/Database'
let's add '~> for everything

2021-03-16 10:54 UTC, TitovEvgeni commented on AudioPlayer/Objects/RequestHandler.swift
> +    private let headers: HTTPHeaders = ["api-key" : "api-key"]
Create fabric with addHeader method. 
```
addHeader(name: String, value: String) -> RequestHandler {
   var new = self
   new.headers[name] = value
   return new
}
```
Then we can call this method in our manager as many times as we like.

2021-03-16 10:54 UTC, TitovEvgeni commented on AudioPlayer/Screens/Music/Controller/MusicViewController.swift
> +        FirebaseHandler().read { [weak self] (response: [String: MusicFirebase]?) in
I'l done it in MVP architecture :)

2021-03-16 13:41 UTC, TitovEvgeni commented on AudioPlayer/AppDelegate.swift
> +//  Created by Titov, Evgeny on 11.03.21.
Done

2021-03-16 14:48 UTC, TitovEvgeni commented on AudioPlayer/AppDelegate.swift
> +        IQKeyboardManager.shared.toolbarManageBehaviour = .byTag
Problem: Massive App Delegate. 
Solution: For my project better create singleton or class with this config. But in big apps maybe better to use classes that represent a single action then combine this classes in one builder and run it.

2021-03-16 15:59 UTC, TitovEvgeni commented on Podfile
> +  pod 'Firebase/Database'
Done.

2021-03-16 15:59 UTC, TitovEvgeni commented on AudioPlayer/Screens/Player/Controller/PlayerViewController.swift
> +            ? sender.setTitle("Pause", for: .normal)
RSwift added.

2021-03-16 16:04 UTC, TitovEvgeni commented on AudioPlayer/Custom View/Cells/Table View/MusicCell/MusicTableViewCell.swift
> +        self.separatorInset = UIEdgeInsets(top: 0, left: 15, bottom: 0, right: 15)
Any const/magic numbers remove inside code. Edgeinsets adde in xib file.

2021-03-16 16:05 UTC, TitovEvgeni commented on AudioPlayer/Helpers/LinearGradient.swift
> +        gradient.endPoint = CGPoint(x: 1, y: 0.5)
Added addGradientPoints method.

2021-03-16 18:30 UTC, TitovEvgeni commented on AudioPlayer/Screens/Player/Controller/PlayerViewController.swift
> +            trackImage.isHidden = false
Implement UIVIew extension for hide/show.

2021-03-18 13:51 UTC, ekazimirova commented on AudioPlayer/AppDelegate.swift
> +        IQKeyboardManager.shared.toolbarManageBehaviour = .byTag
please add TODO (for me for future PR)

2021-03-18 13:53 UTC, ekazimirova commented on AudioPlayer/Custom View/Cells/Table View/MusicCell/MusicTableViewCell.swift
> +            trackImage.showView()
my suggestion to change it
func changeHidden/Visibility(isHidden: bool) {
        self.isHidden = isHidden
    }

2021-03-18 13:54 UTC, ekazimirova commented on AudioPlayer/Extensions/MusicViewController+UISearchBarDelegate.swift
> +            noResultsStackView.showView()
and than it will be just noResultsStackView.setHidden( searchResult?.count == .zero)

2021-03-18 13:55 UTC, ekazimirova commented on AudioPlayer/Objects/RequestHandler.swift
> +    private let headers: HTTPHeaders = ["api-key" : "api-key"]
please, do it

2021-03-18 13:55 UTC, ekazimirova commented on AudioPlayer/Screens/Music/Controller/MusicViewController.swift
> +        FirebaseHandler().read { [weak self] (response: [String: MusicFirebase]?) in
please add TODO

2021-03-19 16:50 UTC, ekazimirova approved these changes

2021-03-19 16:51 UTC, closed without merging